site_name: DDEV-Live

google_analytics:
  - 'UA-105593079-5'
  - 'auto'

theme:
  name: 'material'
  palette:
    primary: 'light-blue'

nav:
    - Home: index.md
    - Introduction and Philosophy: introduction.md
    - Getting Started: getting-started.md
    - Auth and Orgs:
        - Accounts: account-types.md
        - Authentication: authentication.md
        - Administration: administration.md
        - Organizations: organizations.md
    - Providers:
        - Provider: providers.md
        - GitHub: github.md
        - GitLab: gitlab.md
    - Working with Sites:
        - Backups: backups.md
        - Databases: databases.md
        - Execs: exec.md
        - Files: files.md
        - Guides:
            - Drupal: drupal-guide.md
            - TYPO3: typo3-guide.md
            - WordPress: wordpress-guide.md
        - Restores: restores.md
        - Services: services.md
        - Sites: sites.md
        - Jobs: jobs.md
        - Hostnames: hostnames.md
        - TLS: tls.md
        - Variables: variables.md
    - CI/CD:
        - Overview: cicd.md
        - Jenkins: jenkins.md
        - CircleCI: circleci.md
    - Finding Help:
        - Community: placeholder.md
        - Support: support.md
        - FAQs: faq.md
    - About:
        - Roadmap: roadmap.md
        - Known issues: known-issues.md
        - Contributing ⧉: https://github.com/drud/community/blob/master/governance.md
        - License ⧉: https://github.com/drud/docs/blob/master/LICENSE.md

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - def_list
    - mdx_truly_sane_lists:
        nested_indent: 2
        truly_sane: true
    - nl2br
    - pymdownx.details
    - pymdownx.superfences

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        locale: en

extra_javascript:
  - 'js/extra.js'
